# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD9Qv5x-rMwV04aB3YPiox8MNdDtsg2C
"""

# ============================================================
# Q2 - DenseNet + PixelNet
# GUARANTEED 64x64 OUTPUT VERSION
# ============================================================

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

print("TensorFlow:", tf.__version__)

# ------------------------------------------------------------
# 1. Parameters
# ------------------------------------------------------------

IMG_SIZE = 64
NUM_CLASSES = 4
N = 200

# ------------------------------------------------------------
# 2. Create dataset
# ------------------------------------------------------------

np.random.seed(42)

X = np.random.random(
    (N, IMG_SIZE, IMG_SIZE, 3)
).astype(np.float32)

Y = np.random.randint(
    0,
    NUM_CLASSES,
    (N, IMG_SIZE, IMG_SIZE)
)

# One-hot encoding
Y = tf.keras.utils.to_categorical(
    Y,
    NUM_CLASSES
).astype(np.float32)

# Train/test split
X_train = X[:160]
Y_train = Y[:160]

X_test = X[160:]
Y_test = Y[160:]

print("X_train:", X_train.shape)
print("Y_train:", Y_train.shape)
print("X_test :", X_test.shape)
print("Y_test :", Y_test.shape)

# ------------------------------------------------------------
# 3. DenseNet121
# ------------------------------------------------------------

dense_net = tf.keras.applications.DenseNet121(
    include_top=False,
    weights=None,
    input_shape=(64, 64, 3)
)

dense_net.trainable = False

# ------------------------------------------------------------
# 4. Build DenseNet + PixelNet
# ------------------------------------------------------------

inputs = tf.keras.Input(
    shape=(64, 64, 3)
)

# DenseNet feature extraction
x = dense_net(inputs)

print("DenseNet feature shape:", x.shape)

# ------------------------------------------------------------
# PixelNet decoder
# ------------------------------------------------------------

x = tf.keras.layers.Conv2D(
    256,
    3,
    padding="same",
    activation="relu"
)(x)

x = tf.keras.layers.UpSampling2D(
    size=(2, 2)
)(x)

x = tf.keras.layers.Conv2D(
    128,
    3,
    padding="same",
    activation="relu"
)(x)

x = tf.keras.layers.UpSampling2D(
    size=(2, 2)
)(x)

x = tf.keras.layers.Conv2D(
    64,
    3,
    padding="same",
    activation="relu"
)(x)

x = tf.keras.layers.UpSampling2D(
    size=(2, 2)
)(x)

x = tf.keras.layers.Conv2D(
    32,
    3,
    padding="same",
    activation="relu"
)(x)

# ------------------------------------------------------------
# FORCE OUTPUT TO 64 x 64
# ------------------------------------------------------------

x = tf.keras.layers.Resizing(
    64,
    64,
    interpolation="bilinear"
)(x)

# ------------------------------------------------------------
# Pixel-wise classification
# ------------------------------------------------------------

outputs = tf.keras.layers.Conv2D(
    NUM_CLASSES,
    1,
    padding="same",
    activation="softmax"
)(x)

# ------------------------------------------------------------
# Create model
# ------------------------------------------------------------

model = tf.keras.Model(
    inputs=inputs,
    outputs=outputs
)

# ------------------------------------------------------------
# Check shapes BEFORE training
# ------------------------------------------------------------

print("\n======================================")
print("SHAPE CHECK")
print("======================================")

print("Target shape :", Y_train.shape)
print("Model output :", model.output.shape)

# ------------------------------------------------------------
# Compile
# ------------------------------------------------------------

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=0.001
    ),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

# ------------------------------------------------------------
# Train
# ------------------------------------------------------------

print("\n======================================")
print("Starting Training...")
print("======================================\n")

history = model.fit(
    X_train,
    Y_train,
    validation_split=0.2,
    epochs=3,
    batch_size=8,
    verbose=1
)

# ------------------------------------------------------------
# Evaluation
# ------------------------------------------------------------

loss, accuracy = model.evaluate(
    X_test,
    Y_test,
    verbose=0
)

print("\n======================================")
print("Q2 FINAL RESULT")
print("======================================")

print("Test Loss     :", round(loss, 4))
print("Pixel Accuracy:", round(accuracy, 4))

# ------------------------------------------------------------
# Prediction
# ------------------------------------------------------------

prediction = model.predict(
    X_test[:1],
    verbose=0
)

predicted_mask = np.argmax(
    prediction[0],
    axis=-1
)

actual_mask = np.argmax(
    Y_test[0],
    axis=-1
)

# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(X_test[0])
plt.title("Input Road Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(actual_mask)
plt.title("Actual Segmentation")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(predicted_mask)
plt.title("Predicted Segmentation")
plt.axis("off")

plt.tight_layout()
plt.show()
