# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD9Qv5x-rMwV04aB3YPiox8MNdDtsg2C
"""

# Q3: Bidirectional RNN Encoder-Decoder
# Multilingual Translation Demonstration

import tensorflow as tf
import numpy as np

print("TensorFlow Version:", tf.__version__)

# --------------------------------------------------
# 1. Small translation dataset
# --------------------------------------------------

english = [
    "hello",
    "how are you",
    "good morning",
    "thank you",
    "good night",
    "welcome",
    "see you"
]

french = [
    "bonjour",
    "comment allez vous",
    "bonjour matin",
    "merci",
    "bonne nuit",
    "bienvenue",
    "a bientot"
]

# Add special tokens
french_target = [
    "<start> bonjour <end>",
    "<start> comment allez vous <end>",
    "<start> bonjour matin <end>",
    "<start> merci <end>",
    "<start> bonne nuit <end>",
    "<start> bienvenue <end>",
    "<start> a bientot <end>"
]

# --------------------------------------------------
# 2. Tokenization
# --------------------------------------------------

eng_tokenizer = tf.keras.preprocessing.text.Tokenizer()
fra_tokenizer = tf.keras.preprocessing.text.Tokenizer(
    filters=""
)

eng_tokenizer.fit_on_texts(english)
fra_tokenizer.fit_on_texts(french_target)

encoder_input = eng_tokenizer.texts_to_sequences(english)
decoder_input = fra_tokenizer.texts_to_sequences(french_target)

MAX_ENC = max(map(len, encoder_input))
MAX_DEC = max(map(len, decoder_input))

encoder_input = tf.keras.preprocessing.sequence.pad_sequences(
    encoder_input,
    maxlen=MAX_ENC,
    padding="post"
)

decoder_input = tf.keras.preprocessing.sequence.pad_sequences(
    decoder_input,
    maxlen=MAX_DEC,
    padding="post"
)

# Decoder target is shifted by one position
decoder_target = np.zeros_like(decoder_input)

decoder_target[:, :-1] = decoder_input[:, 1:]

print("Encoder Input Shape:", encoder_input.shape)
print("Decoder Input Shape:", decoder_input.shape)

# --------------------------------------------------
# 3. Encoder
# --------------------------------------------------

ENC_VOCAB = len(eng_tokenizer.word_index) + 1
DEC_VOCAB = len(fra_tokenizer.word_index) + 1

encoder_inputs = tf.keras.Input(
    shape=(MAX_ENC,)
)

encoder_embedding = tf.keras.layers.Embedding(
    ENC_VOCAB,
    64
)(encoder_inputs)

encoder_bi = tf.keras.layers.Bidirectional(
    tf.keras.layers.LSTM(
        64,
        return_sequences=False,
        return_state=True
    )
)

encoder_output, fh, fc, bh, bc = encoder_bi(
    encoder_embedding
)

# Merge forward and backward states
state_h = tf.keras.layers.Concatenate()([fh, bh])
state_c = tf.keras.layers.Concatenate()([fc, bc])

# --------------------------------------------------
# 4. Decoder
# --------------------------------------------------

decoder_inputs = tf.keras.Input(
    shape=(MAX_DEC,)
)

decoder_embedding = tf.keras.layers.Embedding(
    DEC_VOCAB,
    128
)(decoder_inputs)

decoder_lstm = tf.keras.layers.LSTM(
    128,
    return_sequences=True
)

decoder_output = decoder_lstm(
    decoder_embedding,
    initial_state=[state_h, state_c]
)

decoder_dense = tf.keras.layers.Dense(
    DEC_VOCAB,
    activation="softmax"
)

outputs = decoder_dense(decoder_output)

# --------------------------------------------------
# 5. Create model
# --------------------------------------------------

model = tf.keras.Model(
    [encoder_inputs, decoder_inputs],
    outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# --------------------------------------------------
# 6. Train
# --------------------------------------------------

history = model.fit(
    [encoder_input, decoder_input],
    np.expand_dims(decoder_target, -1),
    epochs=100,
    batch_size=2,
    verbose=0
)

print("\nTraining completed successfully.")

# --------------------------------------------------
# 7. Training accuracy
# --------------------------------------------------

print(
    "Final Training Accuracy:",
    round(history.history["accuracy"][-1], 4)
)
