# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD9Qv5x-rMwV04aB3YPiox8MNdDtsg2C
"""

import tensorflow as tf
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
import numpy as np

# Pre-trained CNN
base = ResNet50(weights='imagenet', include_top=False,
                input_shape=(224,224,3))

# Freeze CNN layers
base.trainable = False

# Classification layer
x = GlobalAveragePooling2D()(base.output)
x = Dense(64, activation='relu')(x)
output = Dense(1, activation='sigmoid')(x)

model = Model(base.input, output)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.summary()

# Test with a sample image
img = np.random.rand(1,224,224,3).astype('float32')
prediction = model.predict(img)

print("Cancer probability:", prediction[0][0])
print("Prediction:", "Malignant" if prediction[0][0] > 0.5 else "Benign")
