# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD9Qv5x-rMwV04aB3YPiox8MNdDtsg2C
"""

# Q4: LSTM Stock Price Prediction
# BPTT Demonstration

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

print("TensorFlow Version:", tf.__version__)

# --------------------------------------------------
# 1. Generate historical stock-like data
# --------------------------------------------------

np.random.seed(42)

time = np.arange(500)

prices = (
    100
    + 0.05 * time
    + 5 * np.sin(time / 20)
    + np.random.normal(0, 1, 500)
)

# --------------------------------------------------
# 2. Normalize data
# --------------------------------------------------

minimum = prices.min()
maximum = prices.max()

normalized = (
    prices - minimum
) / (
    maximum - minimum
)

# --------------------------------------------------
# 3. Create sequences
# --------------------------------------------------

SEQ_LEN = 20

X = []
Y = []

for i in range(len(normalized) - SEQ_LEN):
    X.append(normalized[i:i+SEQ_LEN])
    Y.append(normalized[i+SEQ_LEN])

X = np.array(X)
Y = np.array(Y)

X = X.reshape(
    X.shape[0],
    X.shape[1],
    1
)

# Train/test split
split = int(0.8 * len(X))

X_train = X[:split]
Y_train = Y[:split]

X_test = X[split:]
Y_test = Y[split:]

print("Training Shape:", X_train.shape)
print("Testing Shape :", X_test.shape)

# --------------------------------------------------
# 4. LSTM model
# --------------------------------------------------

model = tf.keras.Sequential([
    tf.keras.layers.LSTM(
        64,
        input_shape=(SEQ_LEN, 1),
        return_sequences=False
    ),

    tf.keras.layers.Dense(32, activation="relu"),

    tf.keras.layers.Dense(1)
])

model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

model.summary()

# --------------------------------------------------
# 5. Train
# --------------------------------------------------

history = model.fit(
    X_train,
    Y_train,
    epochs=10,
    batch_size=16,
    validation_split=0.1,
    verbose=1
)

# --------------------------------------------------
# 6. Prediction
# --------------------------------------------------

predicted = model.predict(X_test)

# Convert back to original scale
predicted_prices = (
    predicted.flatten()
    * (maximum - minimum)
    + minimum
)

actual_prices = (
    Y_test
    * (maximum - minimum)
    + minimum
)

# --------------------------------------------------
# 7. Evaluation
# --------------------------------------------------

loss, mae = model.evaluate(
    X_test,
    Y_test,
    verbose=0
)

print("\nTest MSE:", round(loss, 5))
print("Test MAE:", round(mae, 5))

# --------------------------------------------------
# 8. Plot prediction
# --------------------------------------------------

plt.figure(figsize=(12,5))

plt.plot(
    actual_prices,
    label="Actual Price"
)

plt.plot(
    predicted_prices,
    label="Predicted Price"
)

plt.title("LSTM Stock Price Prediction")
plt.xlabel("Time")
plt.ylabel("Stock Price")
plt.legend()
plt.show()
