# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vD9Qv5x-rMwV04aB3YPiox8MNdDtsg2C
"""

# Q5: Video Caption Generation
# Transfer Learning + LSTM Encoder-Decoder

import tensorflow as tf
import numpy as np

print("TensorFlow Version:", tf.__version__)

# --------------------------------------------------
# 1. Transfer Learning CNN
# --------------------------------------------------

IMG_SIZE = 128

cnn = tf.keras.applications.MobileNetV2(
    weights="imagenet",
    include_top=False,
    pooling="avg",
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

# Freeze CNN
cnn.trainable = False

print("CNN loaded successfully.")
print("Trainable CNN layers:", sum(
    layer.trainable for layer in cnn.layers
))

# --------------------------------------------------
# 2. Simulate video frames
# --------------------------------------------------

NUM_VIDEOS = 20
FRAMES = 5
FEATURE_SIZE = 1280

video_frames = np.random.rand(
    NUM_VIDEOS,
    FRAMES,
    IMG_SIZE,
    IMG_SIZE,
    3
).astype("float32")

# Preprocess frames
frames = video_frames.reshape(
    NUM_VIDEOS * FRAMES,
    IMG_SIZE,
    IMG_SIZE,
    3
)

frames = tf.keras.applications.mobilenet_v2.preprocess_input(
    frames
)

# --------------------------------------------------
# 3. Extract visual features
# --------------------------------------------------

features = cnn.predict(
    frames,
    verbose=0
)

features = features.reshape(
    NUM_VIDEOS,
    FRAMES,
    FEATURE_SIZE
)

print("Video Feature Shape:", features.shape)

# --------------------------------------------------
# 4. Caption dataset
# --------------------------------------------------

captions = [
    "<start> a person is walking <end>",
    "<start> a car is moving <end>",
    "<start> people are crossing road <end>",
    "<start> a vehicle is on road <end>",
    "<start> a person is running <end>"
]

tokenizer = tf.keras.preprocessing.text.Tokenizer(
    filters=""
)

tokenizer.fit_on_texts(captions)

caption_sequences = tokenizer.texts_to_sequences(
    captions
)

MAX_LEN = max(
    len(x) for x in caption_sequences
)

caption_sequences = tf.keras.preprocessing.sequence.pad_sequences(
    caption_sequences,
    maxlen=MAX_LEN,
    padding="post"
)

VOCAB_SIZE = len(tokenizer.word_index) + 1

# Repeat captions to match video examples
caption_sequences = np.tile(
    caption_sequences,
    (4, 1)
)[:NUM_VIDEOS]

# Decoder input
decoder_input = caption_sequences[:, :-1]

# Decoder target
decoder_target = caption_sequences[:, 1:]

# --------------------------------------------------
# 5. LSTM Encoder
# --------------------------------------------------

video_input = tf.keras.Input(
    shape=(FRAMES, FEATURE_SIZE),
    name="video_features"
)

encoder = tf.keras.layers.LSTM(
    256,
    return_state=True
)

_, state_h, state_c = encoder(
    video_input
)

# --------------------------------------------------
# 6. Caption Decoder
# --------------------------------------------------

caption_input = tf.keras.Input(
    shape=(MAX_LEN - 1,),
    name="caption_input"
)

embedding = tf.keras.layers.Embedding(
    VOCAB_SIZE,
    256
)(caption_input)

decoder = tf.keras.layers.LSTM(
    256,
    return_sequences=True
)

decoder_output = decoder(
    embedding,
    initial_state=[state_h, state_c]
)

output = tf.keras.layers.Dense(
    VOCAB_SIZE,
    activation="softmax"
)(decoder_output)

# --------------------------------------------------
# 7. Complete model
# --------------------------------------------------

model = tf.keras.Model(
    [video_input, caption_input],
    output
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# --------------------------------------------------
# 8. Train
# --------------------------------------------------

history = model.fit(
    [features, decoder_input],
    np.expand_dims(decoder_target, -1),
    epochs=5,
    batch_size=4,
    verbose=1
)

print("\nCaption model training completed.")

print(
    "Final Training Accuracy:",
    round(history.history["accuracy"][-1], 4)
)
