# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzH6u4WoDDU3KVzfJ6xZ_yK-2Wq253yM
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import DenseNet121

print("Q2: DENSENET + PIXEL-WISE SEGMENTATION")
print("=" * 45)

IMG_SIZE = 128
NUM_CLASSES = 5

# Input
inputs = layers.Input(
    shape=(IMG_SIZE, IMG_SIZE, 3)
)

# DenseNet
backbone = DenseNet121(
    weights="imagenet",
    include_top=False,
    input_tensor=inputs
)

# Freeze pretrained layers
backbone.trainable = False

# Feature extraction
x = backbone.output

# Decoder
x = layers.Conv2D(
    128,
    3,
    padding="same",
    activation="relu"
)(x)

x = layers.Conv2D(
    64,
    3,
    padding="same",
    activation="relu"
)(x)

# Resize to original image
x = layers.Resizing(
    IMG_SIZE,
    IMG_SIZE
)(x)

# Pixel-wise prediction
outputs = layers.Conv2D(
    NUM_CLASSES,
    1,
    activation="softmax"
)(x)

# Model
model = Model(
    inputs,
    outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Demonstration dataset
X_train = np.random.rand(
    10,
    IMG_SIZE,
    IMG_SIZE,
    3
).astype("float32")

y_train = np.random.randint(
    0,
    NUM_CLASSES,
    (
        10,
        IMG_SIZE,
        IMG_SIZE
    )
)

print("\nTraining model...")

model.fit(
    X_train,
    y_train,
    epochs=2,
    batch_size=2,
    verbose=1
)

# Prediction
sample = X_train[0:1]

prediction = model.predict(
    sample,
    verbose=0
)

segmentation = np.argmax(
    prediction[0],
    axis=-1
)

print("\nRESULT")
print("Input Shape:",
      sample.shape)

print("Output Shape:",
      prediction.shape)

print("Pixel Map Shape:",
      segmentation.shape)

print("\nClasses:")

print("0 = Road")
print("1 = Car")
print("2 = Pedestrian")
print("3 = Building")
print("4 = Vegetation")

print("\nDetected Pixel Classes:")
print(np.unique(segmentation))

print("\nProgram completed successfully.")
