# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzH6u4WoDDU3KVzfJ6xZ_yK-2Wq253yM
"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from sklearn.preprocessing import MinMaxScaler

print("Q4: LSTM + BPTT STOCK MARKET PREDICTION")
print("=" * 45)

np.random.seed(42)

# Generate stock prices
days = 200

prices = 100 + np.cumsum(
    np.random.randn(days)
)

# Normalize
scaler = MinMaxScaler()

scaled = scaler.fit_transform(
    prices.reshape(-1, 1)
)

# Create sequences
window = 10

X = []
y = []

for i in range(
    len(scaled) - window
):

    X.append(
        scaled[i:i + window]
    )

    if scaled[i + window] > scaled[i + window - 1]:
        y.append(1)
    else:
        y.append(0)

X = np.array(X)
y = np.array(y)

# Train/test split
split = int(len(X) * 0.8)

X_train = X[:split]
X_test = X[split:]

y_train = y[:split]
y_test = y[split:]

print("Training Samples:",
      len(X_train))

print("Testing Samples:",
      len(X_test))

# LSTM
model = Sequential()

model.add(
    LSTM(
        32,
        return_sequences=True,
        input_shape=(window, 1)
    )
)

model.add(
    Dropout(0.2)
)

model.add(
    LSTM(16)
)

model.add(
    Dense(
        8,
        activation="relu"
    )
)

model.add(
    Dense(
        1,
        activation="sigmoid"
    )
)

# Compile
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("\nTraining LSTM...")

model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=8,
    validation_data=(X_test, y_test),
    verbose=1
)

# Evaluate
loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print("\nRESULT")
print("Test Loss:",
      round(loss, 4))

print("Test Accuracy:",
      round(accuracy * 100, 2),
      "%")

# Prediction
sample = X_test[-1].reshape(
    1,
    window,
    1
)

prediction = model.predict(
    sample,
    verbose=0
)

probability = prediction[0][0]

print("\nUP Probability:",
      round(probability * 100, 2),
      "%")

if probability >= 0.5:
    print("Predicted Trend: UP")
else:
    print("Predicted Trend: DOWN")

print("\nBPTT:")
print("Backpropagation Through Time")
print("is used to train the LSTM")
print("across the time sequence.")

print("\nProgram completed successfully.")
