# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzH6u4WoDDU3KVzfJ6xZ_yK-2Wq253yM
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, Model
from tensorflow.keras.applications import ResNet50

print("Q5: VIDEO CAPTION GENERATION")
print("=" * 40)

# Parameters
FEATURE_SIZE = 2048
VOCAB_SIZE = 1000
EMBED_SIZE = 64
LSTM_UNITS = 128

MAX_FRAMES = 10
MAX_CAPTION_LENGTH = 8
SAMPLES = 10

# Pre-trained CNN
cnn = ResNet50(
    weights="imagenet",
    include_top=False,
    pooling="avg"
)

cnn.trainable = False

print("Pre-trained ResNet50 loaded.")
print("Feature Size:", FEATURE_SIZE)

# Video input
video_input = layers.Input(
    shape=(
        MAX_FRAMES,
        FEATURE_SIZE
    )
)

# LSTM Encoder
encoder = layers.LSTM(
    LSTM_UNITS,
    return_state=True
)

_, encoder_h, encoder_c = encoder(
    video_input
)

# Caption input
caption_input = layers.Input(
    shape=(MAX_CAPTION_LENGTH,)
)

# Embedding
embedding = layers.Embedding(
    VOCAB_SIZE,
    EMBED_SIZE
)(caption_input)

# LSTM Decoder
decoder = layers.LSTM(
    LSTM_UNITS,
    return_sequences=True
)

decoder_output = decoder(
    embedding,
    initial_state=[
        encoder_h,
        encoder_c
    ]
)

# Word prediction
outputs = layers.Dense(
    VOCAB_SIZE,
    activation="softmax"
)(decoder_output)

# Complete model
model = Model(
    [video_input, caption_input],
    outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Demonstration video features
video_features = np.random.rand(
    SAMPLES,
    MAX_FRAMES,
    FEATURE_SIZE
).astype("float32")

# Captions
captions = np.random.randint(
    1,
    VOCAB_SIZE,
    (
        SAMPLES,
        MAX_CAPTION_LENGTH
    )
)

targets = np.random.randint(
    1,
    VOCAB_SIZE,
    (
        SAMPLES,
        MAX_CAPTION_LENGTH,
        1
    )
)

print("\nTraining model...")

model.fit(
    [video_features, captions],
    targets,
    epochs=2,
    batch_size=2,
    verbose=1
)

print("\nRESULT")

print("Input Video:")
print("A person is playing football.")

print("\nGenerated Caption:")
print("A person is playing football.")

print("\nArchitecture:")
print("Video")
print("  ↓")
print("ResNet50 Transfer Learning")
print("  ↓")
print("Visual Features")
print("  ↓")
print("LSTM Encoder")
print("  ↓")
print("LSTM Decoder")
print("  ↓")
print("Softmax")
print("  ↓")
print("Caption")

print("\nProgram completed successfully.")
