# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11IKtElxmdnK41CmdVB6BwNoSK7J1N7-w
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB0

print("Q1: PLANT DISEASE DETECTION")
print("=" * 40)

IMG_SIZE = 128
NUM_CLASSES = 4

# Data augmentation
augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2)
])

# Pre-trained CNN
base_model = EfficientNetB0(
    weights="imagenet",
    include_top=False,
    input_shape=(IMG_SIZE, IMG_SIZE, 3)
)

# Freeze CNN layers
base_model.trainable = False

# Model
inputs = layers.Input(
    shape=(IMG_SIZE, IMG_SIZE, 3)
)

x = augmentation(inputs)
x = base_model(x, training=False)
x = layers.GlobalAveragePooling2D()(x)
x = layers.Dropout(0.3)(x)

outputs = layers.Dense(
    NUM_CLASSES,
    activation="softmax"
)(x)

model = models.Model(inputs, outputs)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Demonstration dataset
X_train = np.random.rand(
    40, IMG_SIZE, IMG_SIZE, 3
).astype("float32")

y_train = np.random.randint(
    0, NUM_CLASSES, 40
)

X_test = np.random.rand(
    10, IMG_SIZE, IMG_SIZE, 3
).astype("float32")

y_test = np.random.randint(
    0, NUM_CLASSES, 10
)

# Training
print("\nTraining model...")

model.fit(
    X_train,
    y_train,
    epochs=2,
    batch_size=4,
    verbose=1
)

# Evaluation
loss, accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print("\nRESULT")
print("Test Loss:", round(loss, 4))
print("Test Accuracy:",
      round(accuracy * 100, 2), "%")

# Prediction
classes = [
    "Healthy",
    "Bacterial Disease",
    "Fungal Disease",
    "Viral Disease"
]

prediction = model.predict(
    X_test[0:1],
    verbose=0
)

index = np.argmax(prediction[0])

print("Predicted Disease:",
      classes[index])

print("Confidence:",
      round(np.max(prediction[0]) * 100, 2),
      "%")

print("\nProgram completed successfully.")
