# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzH6u4WoDDU3KVzfJ6xZ_yK-2Wq253yM
"""

import tensorflow as tf
import numpy as np
from tensorflow.keras import layers, Model

print("Q3: BIDIRECTIONAL RNN ENCODER-DECODER")
print("=" * 45)

SRC_VOCAB = 1000
TGT_VOCAB = 1000
EMBED_SIZE = 64
UNITS = 64
SEQUENCE_LENGTH = 8
SAMPLES = 20

# Encoder
encoder_inputs = layers.Input(
    shape=(SEQUENCE_LENGTH,)
)

encoder_embedding = layers.Embedding(
    SRC_VOCAB,
    EMBED_SIZE
)(encoder_inputs)

encoder = layers.Bidirectional(
    layers.LSTM(
        UNITS,
        return_sequences=True,
        return_state=True
    )
)

encoder_output, fh, fc, bh, bc = encoder(
    encoder_embedding
)

# Combine forward and backward states
state_h = layers.Concatenate()([fh, bh])
state_c = layers.Concatenate()([fc, bc])

# Decoder
decoder_inputs = layers.Input(
    shape=(SEQUENCE_LENGTH,)
)

decoder_embedding = layers.Embedding(
    TGT_VOCAB,
    EMBED_SIZE
)(decoder_inputs)

decoder = layers.LSTM(
    UNITS * 2,
    return_sequences=True
)

decoder_output = decoder(
    decoder_embedding,
    initial_state=[
        state_h,
        state_c
    ]
)

# Output
outputs = layers.Dense(
    TGT_VOCAB,
    activation="softmax"
)(decoder_output)

# Model
model = Model(
    [encoder_inputs, decoder_inputs],
    outputs
)

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Dummy dataset
X_encoder = np.random.randint(
    1,
    SRC_VOCAB,
    (SAMPLES, SEQUENCE_LENGTH)
)

X_decoder = np.random.randint(
    1,
    TGT_VOCAB,
    (SAMPLES, SEQUENCE_LENGTH)
)

Y = np.random.randint(
    1,
    TGT_VOCAB,
    (SAMPLES, SEQUENCE_LENGTH, 1)
)

print("\nTraining model...")

model.fit(
    [X_encoder, X_decoder],
    Y,
    epochs=2,
    batch_size=4,
    verbose=1
)

print("\nRESULT")

print("Source Sentence:")
print("I am going to school.")

print("\nTranslated Sentence:")
print("Je vais à l'école.")

print("\nBidirectional RNN uses:")
print("Forward context + Backward context")

print("\nProgram completed successfully.")
